---
- name: Install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Install haproxy configuration
  template:
    src: "../templates/haproxy.cfg.j2"
    dest: "{{ haproxy_config }}"

- name: Create haproxy server cert symlink
  file:
    state: link
    src: "{{ haproxy_ssl_dir }}/certs/tls.crt"
    dest: "{{ haproxy_ssl_dir }}/octoprint.pem"
  when: octoprint_ssl_enabled|bool

- name: Create haproxy server key symlink
  file:
    state: link
    src: "{{ haproxy_ssl_dir }}/private/tls.key"
    dest: "{{ haproxy_ssl_dir }}/octoprint.pem.key"
  when: octoprint_ssl_enabled|bool

- name: Copy over 503-no-octoprint file
  copy:
    src: "../files/503-no-octoprint.http"
    dest: "/etc/haproxy/errors/503-no-octoprint.http"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Copy over 503-no-webcam file
  copy:
    src: "../files/503-no-webcam.http"
    dest: "/etc/haproxy/errors/503-no-webcam.http"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Copy over 503-no-webcam-hls file
  copy:
    src: "../files/503-no-webcam-hls.http"
    dest: "/etc/haproxy/errors/503-no-webcam-hls.http"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Validate haproxy configuration
  shell: "haproxy -c -f {{ haproxy_config }}"
  register: haproxy_validate

- debug:
    msg: "{{ haproxy_validate.stdout }}"

- name: Start haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: true
    daemon_reload: true
