---
python_version: "3.11"
python_packages:
  - "python{{ python_version }}"
  - "python3-pip"
  - "python3-dev"
  - "python3-setuptools"
  - "python3-venv"
packages:
  - "git"
  - "libyaml-dev"
  - "build-essential"
  - "libffi-dev"
  - "libssl-dev"
  - "haproxy"

webcam_packages:
  - "subversion"
  - "libjpeg62-turbo-dev"
  - "imagemagick"
  - "ffmpeg"
  - "libv4l-dev"
  - "cmake"

# octoprint
octoprint_version: "1.10.2"
octoprint_base_dir: "/opt/OctoPrint"
octoprint_user: "octoprint"
octoprint_group: "{{ octoprint_user }}"
octoprint_web_port: 5000
octoprint_ssl_enabled: "{{ octoprint.ssl_enabled|d(false|bool) }}"
octoprint_venv_cmd: "python3 -m venv {{ octoprint_base_dir }}"
octoprint_webcam_port: 8080
octoprint_sudoer_actions:
  - "/sbin/shutdown"
  - "/usr/sbin/service"

# haproxy
haproxy_user: "haproxy"
haproxy_group: "haproxy"
haproxy_ssl_dir: "/etc/ssl"
haproxy_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
haproxy_config: "/etc/haproxy/haproxy.cfg"
