---
# Install OS common packages and configuration
- name: Prequisites
  tags: common,packages
  hosts: sbc
  tasks:
    - import_role:
        name: common

# Install Notification Script
- name: Installing Notification scripts
  tags: notification
  hosts: sbc
  tasks:
    - import_role:
        name: notification
      when: notification.enabled|bool

# Install NUT
- name: Installing NUT
  tags: nut
  hosts: sbc
  tasks:
    - import_role:
        name: nut
      when: nut.enabled|bool

# Install pfsense script
- name: Installing pfsense backup
  tags: pfsense
  hosts: sbc
  tasks:
    - import_role:
        name: pfsense
      when: pfsense.enabled|bool

# Install node exporter
- name: Installing Node Exporter
  tags: node_exporter
  hosts: sbc
  tasks:
    - import_role:
        name: node_exporter

# Install Octoprint
- name: Installing Octoprint
  tags: octoprint
  hosts: sbc
  tasks:
    - import_role:
        name: octoprint
      when: octoprint.install|bool
