common_packages:
  - ca-certificates
  - gnupg
  - vim
  - git
  - curl
  - netcat-openbsd
  - dnsutils
  - stow
  - tree
  - htop
  - jq
  - rsync

debian_packages:
  - lsb-release
  - nfs-common

os_timezone: "America/Chicago"

ssl_directory: "/etc/ssl"