node_exporter_version: "1.6.1"
system_arch: "{% if ansible_facts.architecture == 'armv7l' %}armv7{% else %}arm64{% endif %}"
exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ system_arch }}.tar.gz"
tmp_package_path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ system_arch }}"
node_exporter_bin_path: "/usr/local/bin"
node_exporter_path: "/var/lib/node_exporter"
node_exporter_user: "node_exporter"
node_exporter_group: "{{ node_exporter_user }}"